export const offersItems = [
    {
      title: "Lamborghini Aventador S",
      price: "$417,650",
      type: "Automatic",
      drive: "Gasoline",
      img: "./offers/aventador.webp",
    },
    {
      title: "Ferrari 488 GTB",
      price: "$334,000",
      type: "Automatic",
      drive: "Gasoline",
      img: "./offers/ferrari.webp",
    },
    {
      title: "Bugatti Chiron",
      price: "$2,990,000",
      type: "Automatic",
      drive: "Gasoline",
      img: "./offers/bugatti.webp",
    },
    {
      title: "Porsche 911 Turbo S",
      price: "$203,500",
      type: "Automatic",
      drive: "Gasoline",
      img: "./offers/porsche.webp",
    },
    {
      title: "Aston Martin DBS Superleggera",
      price: "$308,000",
      type: "Automatic",
      drive: "Gasoline",
      img: "./offers/aston.webp",
    },
    {
      title: "McLaren 720S",
      price: "$299,000",
      type: "Automatic",
      drive: "Gasoline",
      img: "./offers/mclaren.webp",
    },
    {
      title: "Bentley Continental GT",
      price: "$220,000",
      type: "Automatic",
      drive: "Gasoline",
      img: "./offers/bentley.webp",
    },
    {
      title: "Rolls-Royce Ghost",
      price: "$332,500",
      type: "Automatic",
      drive: "Gasoline",
      img: "./offers/rolls.webp",
    },
    {
      title: "Mercedes-AMG GT R Pro ",
      price: "$199,650",
      type: "Automatic",
      drive: "Gasoline",
      img: "./offers/mercedes.webp",
    },
    {
      title: "Audi R8 V10 Plus",
      price: "$197,000",
      type: "Automatic",
      drive: "Gasoline",
      img: "./offers/audi.webp",
    },
    {
      title: "BMW M8 Competition",
      price: "$146,000",
      type: "Automatic",
      drive: "Gasoline",
      img: "./offers/bmw.webp",
    },
    {
      title: "Lexus LC 500",
      price: "$92,950",
      type: "Automatic",
      drive: "Gasoline",
      img: "./offers/lexus.webp",
    },
    {
      title: "Maserati GranTurismo",
      price: "$150,980",
      type: "Automatic",
      drive: "Gasoline",
      img: "./offers/maserati.webp",
    },
    {
      title: "Jaguar F-Type SVR",
      price: "$123,600",
      type: "Automatic",
      drive: "Gasoline",
      img: "./offers/jaguar.webp",
    },
    {
      title: "Acura NSX s",
      price: "$157,500",
      type: "Automatic",
      drive: "Gasoline",
      img: "./offers/acura.webp",
    },
    {
      title: "Alfa Romeo 4C Spider",
      price: "$73,495",
      type: "Automatic",
      drive: "Gasoline",
      img: "./offers/alfa.webp",
    },
    {
      title: "Chevrolet Corvette ZR1",
      price: "$123,000",
      type: "Manual",
      drive: "Gasoline",
      img: "./offers/chevrolet.webp",
    },
    {
      title: "Dodge Viper ACR",
      price: "$120,000",
      type: "Manual",
      drive: "Gasoline",
      img: "./offers/dodge.webp",
    },
    {
      title: "Ford GT",
      price: "$500,000",
      type: "Automatic",
      drive: "Gasoline",
      img: "./offers/ford.webp",
    },
    {
      title: "Nissan GT-R Nismo ",
      price: "$210,740",
      type: "Automatic",
      drive: "Gasoline",
      img: "./offers/nissan.webp",
    },
  ];